Models/ErrorViewModel.cs
using System;

namespace JudgeMyTaste.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FavoriteBand.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace JudgeMyTaste.Models
{
    public class FavoriteBand
    {
        public int Id { get; set; }
         public string Name { get; set; }
          public string EnteredBy { get; set; }
           public DateTime EnteredOn { get; set; }

        
    }
}

Controllers/FavoriteBandsController.cs
using JudgeMyTaste.Data;
using JudgeMyTaste.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging.Abstractions;

namespace Controllers
{
    public class FavoriteBandsController : Controller
    {
        private readonly JudgeMyTasteContext _context;
        private readonly ILogger<FavoriteBandsController> _logger;
        private IConfiguration Configuration;

      

        public FavoriteBandsController(ILogger<FavoriteBandsController> logger,JudgeMyTasteContext context, IConfiguration _configuration)
        {
            _context = context;
            Configuration = _configuration;
            _logger = logger;
        }

        // GET: FavoriteBands
        public async Task<IActionResult> Index()
        {
            Task<string> x = GetAsync(1);
            return View(await _context.FavoriteBands.ToListAsync());

        }

        // GET: FavoriteBands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
           // Task<string>  x = GetAsync();
            var favoriteBand = await _context.FavoriteBands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favoriteBand == null)
            {
                return NotFound();
            }

            return View(favoriteBand);
        }

        private async Task<string> GetAsync(int?id)
        {
           
            var query = $"SELECT Name FROM FavoriteBands WHERE Id = " + id;
            var rvalue = string.Empty;
            var connection = new SqlConnection(Configuration.GetConnectionString("MS_TableConnectionString"));
            //using (var connection = new SqlConnection(Configuration.GetConnectionString("MS_TableConnectionString")))
            //{
           // connection.Open();
                var watch = System.Diagnostics.Stopwatch.StartNew();
                var orderDetail = await connection.QuerySingleOrDefaultAsync<string>(query).ConfigureAwait(true);
                watch.Stop();
            
                _logger.LogInformation("Elapsed during DB select request: " + watch.ElapsedMilliseconds + "ms", NullLogger.Instance);
                _logger.LogInformation("SELECT returned " + orderDetail);

                rvalue = orderDetail;
                // FiddleHelper.WriteTable(new List<OrderDetail>() { orderDetail });
           // }
            return rvalue;

        }

// GET: FavoriteBands/Create
public IActionResult Create()
        {
            return View();
        }

        // POST: FavoriteBands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.



    [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,EnteredBy,EnteredOn")] FavoriteBand favoriteBand)
        {

           
            if (ModelState.IsValid)
            {
                _context.Add(favoriteBand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(favoriteBand);
        }

        // GET: FavoriteBands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Task<string> x = GetAsync(id);
            var favoriteBand = await _context.FavoriteBands.FindAsync(id);
            if (favoriteBand == null)
            {
                return NotFound();
            }
            return View(favoriteBand);
        }

        // POST: FavoriteBands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,EnteredBy,EnteredOn")] FavoriteBand favoriteBand)
        {
            if (id != favoriteBand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favoriteBand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoriteBandExists(favoriteBand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(favoriteBand);
        }

        // GET: FavoriteBands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteBand = await _context.FavoriteBands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favoriteBand == null)
            {
                return NotFound();
            }

            return View(favoriteBand);
        }

        // POST: FavoriteBands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var favoriteBand = await _context.FavoriteBands.FindAsync(id);
            _context.FavoriteBands.Remove(favoriteBand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoriteBandExists(int id)
        {
            return _context.FavoriteBands.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using JudgeMyTaste.Models;

namespace JudgeMyTaste.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FavoriteBands/Create.cshtml
@model JudgeMyTaste.Models.FavoriteBand

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FavoriteBand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnteredBy" class="control-label"></label>
                <input asp-for="EnteredBy" class="form-control" />
                <span asp-validation-for="EnteredBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnteredOn" class="control-label"></label>
                <input asp-for="EnteredOn" class="form-control" />
                <span asp-validation-for="EnteredOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/FavoriteBands/Delete.cshtml
@model JudgeMyTaste.Models.FavoriteBand

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FavoriteBand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredOn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/FavoriteBands/Details.cshtml
@model JudgeMyTaste.Models.FavoriteBand

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FavoriteBand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnteredOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnteredOn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FavoriteBands/Edit.cshtml
@model JudgeMyTaste.Models.FavoriteBand

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FavoriteBand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnteredBy" class="control-label"></label>
                <input asp-for="EnteredBy" class="form-control" />
                <span asp-validation-for="EnteredBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnteredOn" class="control-label"></label>
                <input asp-for="EnteredOn" class="form-control" />
                <span asp-validation-for="EnteredOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/FavoriteBands/Index.cshtml
@model IEnumerable<JudgeMyTaste.Models.FavoriteBand>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnteredBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnteredOn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnteredBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnteredOn)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JudgeMyTaste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JudgeMyTaste</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="FavoriteBands" asp-action="Index">Favorite Bands</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - JudgeMyTaste - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>